apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: k8s-jobs-b-
spec:
  entrypoint: pi-tmpl
  templates:
  - name: pi-tmpl
    resource:                   # indicates that this is a resource template
      action: create            # can be any kubectl action (e.g. create, delete, apply, patch)
      # The successCondition and failureCondition are optional expressions.
      # If failureCondition is true, the step is considered failed.
      # If successCondition is true, the step is considered successful.
      # They use kubernetes label selection syntax and can be applied against any field
      # of the resource (not just labels). Multiple AND conditions can be represented by comma
      # delimited expressions.
      # For more details: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
      #successCondition: status.phase = "Running"
      #failureCondition: status.failed > 3
      manifest: |               #put your kubernetes spec here 
        apiVersion: extensions/v1beta1
        kind: Deployment
        metadata:
          name: nginx
        spec:
          replicas: 1
          template:
            metadata:
              labels:
                version: v1
                app: nginx
            spec:
              containers:
              - name: nginx
                image: nginx
                resources:
                  limits:
                    cpu: "0.5"
                    memory: "1G"
                  requests:
                    cpu: "0.5"
                    memory: "1G"
                ports:
                - containerPort: 80
